### ISSUE TITLE
links not working

### ISSUE THREAD

**Issue by finanalyst** [OleVik/grav-plugin-fullpage#5]
The links to demo and contents in your README are broken.

**Comment by coevolving** [comment]
@OleVik I'm confirming the prior issue that "demo is available" pointing at https://olevik.me/plugins/fullpage/book resolves to "Page not Found", as well as "by the plugin" pointing to https://olevik.me/plugins/fullpage/ .

In the meantime, I'm puzzling through "Fullpage Plugin Demo Content" at https://github.com/OleVik/grav-plugin-fullpage/tree/demo-content , surfing down through the book and docs directories.

**Comment by OleVik** [comment]
Fixed with current `master`-branch, and [v1.2.1](https://github.com/OleVik/grav-plugin-fullpage/releases/tag/v1.2.1). As @coevolving notes, demo content is in the `demo-content`-branch. Note that the contents of the repo's README are authoritative as documentation, per the blueprint, the docs on the site may not be as current.
